name: news_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  equatable: ^2.0.5
  go_router: ^6.0.9
  flutter_native_splash: ^2.2.16
  shared_preferences: ^2.0.17
  logger: ^1.1.0
  http: ^0.13.5
  intl: ^0.18.0
  envied: ^0.3.0
  flutter_svg: ^1.1.6
  fpdart: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.1.0
  build_runner: ^2.3.3
  envied_generator: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_icons:
  image_path: assets/icons/ic_app.png
  android: true
  ios: true

flutter_native_splash:
  image: assets/icons/ic_app.png
  color: "#FAEBD7"
  android_12:
    image: assets/icons/ic_app.png
    color: "#FAEBD7"
